### ISSUE TITLE
Question about Bts*

### ISSUE THREAD

**Issue by 07hyx06** [zhenpeiyang/MVS2D#1]
> Additionally, we use an asterisk sign ‘∗’ to denote an oracle version Bts∗, where we use the ground truth depth map to
factor out the global scale.

Is it means that the mono depth network's prediction may not have the same scale as the depth map and Bts* is to estimate some parameter (e.g. mean and std in (depth-mean)/std) to adjust its scale according to the gt depth map?

**Comment by zhenpeiyang** [comment]
Hi @07hyx06 , right, mono depth estimators such as Bts do not have accurate scale estimation. In Bts*, we use median scaling to correct the scale factor before evaluating depth error.
