### ISSUE TITLE
Convergence speed

### ISSUE THREAD

**Issue by AddASecond** [zhenpeiyang/MVS2D#10]
hi I have some questions on convergence speed of MVS2D

the cost-volume based method (MVSNet, etc.) can see the outline of objects after 1 epoch or even several iters
![depth_estgt (9)](https://user-images.githubusercontent.com/12587374/156575235-e13e6cf5-b269-469d-b6ab-d7eeb10877f9.png)

however, MVS2D seems hard to convergence and the depthmap are very vague at the beginning.
![depth_estgt (35)](https://user-images.githubusercontent.com/12587374/156575169-5704ab0e-d339-418f-958a-411c48d796f2.png)

does this due to the network design?
Could you explain about this phenomenon?

**Comment by zhenpeiyang** [comment]
Hi @AddASecond , it might related to fact that in our design the multi-view cues are injected in an early stage of the network, and relies on the following 2d conv network to pick up the information.

**Comment by yueruchen** [comment]
@AddASecond 
Hi, are these figures from training set or testing set?

Best,
