### ISSUE TITLE
Question about generalization

### ISSUE THREAD

**Issue by Yannnnnnnnnnnn** [zhenpeiyang/MVS2D#16]
Thanks for sharing of code.

But I wonder why you did not test your method on 7Scenes or Tanks&Temple. 

Besides, I tried to test your method on 7Scenes, but the results are pretty poor. 
Can you give me some suggestions?

My code is here: [https://github.com/Yannnnnnnnnnnn/MVS2D.git at test_7scenes_long](https://github.com/Yannnnnnnnnnnn/MVS2D/tree/test_7scenes_long), as I use the split from Long.

My results is here:
```
7scenes:{'a1': 0.39494346839485406,
 'a2': 0.6459305167578225,
 'a3': 0.8022140821127047,
 'abs_diff': 0.5733749950019752,
 'abs_diff_median': 0.5094702287105953,
 'abs_rel': 0.32380217413691914,
 'log10': 0.17217029032900052,
 'rmse': 0.6894540686467114,
 'rmse_log': 0.47906266186605484,
 'sq_rel': 0.27828435772756005,
 'thre1': 0.23810647116173855,
 'thre3': 0.5398887457282459,
 'thre5': 0.8326691103244529}
```

**Comment by zhenpeiyang** [comment]
Hi @Yannnnnnnnnnnn ,

Thank you for sharing your 7scenes evaluation code!

[This line](https://github.com/Yannnnnnnnnnnn/MVS2D/blob/47f5221b430f5693db5f34ecef88c8376aba893c/datasets/ScanNet.py#L111) should be 
```
        pose = np.linalg.inv(np.loadtxt(path).astype('float32'))
```
After this change, I got following results:
```
Eval Metrics
{'a1': 0.8047938813746175,
 'a2': 0.9538063681174943,
 'a3': 0.9885236621719559,
 'abs_diff': 0.2656457374047707,
 'abs_diff_median': 0.21512217944159226,
 'abs_rel': 0.15241856737391038,
 'log10': 0.061927069688544556,
 'rmse': 0.349060177402023,
 'rmse_log': 0.18342998863800483,
 'sq_rel': 0.08646917180240374,
 'thre1': 0.5595738674357862,
 'thre3': 0.8523538136208321,
 'thre5': 0.9664181626193664}

```

**Comment by Yannnnnnnnnnnn** [comment]
Thanks for your help.
I did not notice the change of pose.
