### ISSUE TITLE
MVS2D的ScanNet数据集链接失效

### ISSUE THREAD

**Issue by NanCheng2001** [zhenpeiyang/MVS2D#20]
您好，请问可以再传一份MVS2D的ScanNet数据集嘛？Onedrive链接失效了。最好可以传一下百度网盘吗？感激不尽。国内做科研好难。。

**Comment by zhenpeiyang** [comment]
Could you try the download link again? Thanks.

**Comment by NanCheng2001** [comment]
It seems worked！Thank you for your prompt reply!
