### ISSUE TITLE
val set in DTU.py not consistent with those in patchmatch_fusion.py

### ISSUE THREAD

**Issue by AddASecond** [zhenpeiyang/MVS2D#7]
There is a point in your repo that is confusing for newbies(for me), that the val set in DTU.py is not consistent with those in patchmatch_fusion.py

in DTU.py val it is

>             data_set = [
                3, 5, 17, 21, 28, 35, 37, 38, 40, 43, 56, 59, 66, 67, 82, 86,
                106, 117
            ]
however in patchmatch_fusion.py / dtu_pyeval.py it is

>     scans = [
        1, 4, 9, 10, 11, 12, 13, 15, 23, 24, 29, 32, 33, 34, 48, 49, 62, 75,
        77, 110, 114, 118
    ]

hope you could fix it,
 or at least this post may be helpful for users who want to reproduce your great work！

**Comment by zhenpeiyang** [comment]
Hi @AddASecond , in DTU.py, the data sequence  [3, 5, 17, 21, 28, 35, 37, 38, 40, 43, 56, 59, 66, 67, 82, 86,106, 117] is used for validation along training. The scans 1, 4, 9, 10, 11, 12, 13, 15, 23, 24, 29, 32, 33, 34, 48, 49, 62, 75,77, 110, 114, 118
] are DTU'test set, which are used in dtu_pyeval.py and patchmatch_fusion.py. Hope this helps.

**Comment by lemonsstyle** [comment]
> 

Hello, I have encountered an error while running the test.

Traceback (most recent call last):                                                                                                                                                          
  File "/home/west/.conda/envs/d3hc/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/west/.conda/envs/d3hc/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "patchmatch_fusion.py", line 367, in process
    args.att_thres, args.use_conf_thres, args.num_consistent)
  File "patchmatch_fusion.py", line 246, in filter_depth
    f"{base_dir}/scan{scanID}/scan{scanID}-rect_{view+1:03d}*npy")[0],
IndexError: list index out of range

It seems that there is also a problem with the list index? But I changed it to the 3 5 17 sequence you mentioned, which is still wrong..... excuse me，how did you solve it？
